# Generated by Django 4.1.1 on 2022-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='page',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pweight',
            field=models.IntegerField(),
        ),
    ]
